# -*- coding: utf-8 -*-
"""API_evalbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y4lql9R_ITHuDIp9M8hVKZv3MHx9TQUY
"""
## Importing libraries
import nltk
import string
from nltk.corpus import stopwords
nltk.download('stopwords')
import torch
from transformers import BertTokenizer,BertForSequenceClassification

## Initialize BERT tokenizer
tokenizer=BertTokenizer.from_pretrained('bert-base-uncased')

## Function for tokenization
def tokenization(sent1, sent2):
    encoded = tokenizer.encode_plus(
        sent1,sent2,
        add_special_tokens=True,
        padding=True,
        truncation=True,
        return_tensors='pt'
    )
    input_ids = encoded['input_ids']
    attention_masks = encoded['attention_mask']
    return input_ids, attention_masks

## Text cleaning and preprocessing
import string
def remove_special_characters(text):
    translator=str.maketrans('','',string.punctuation)
    return text.translate(translator)

def lower_case(text):
    text=text.lower()
    return text

def remove_stopwords(text):
    words=text.split()
    stop_words=set(stopwords.words('english'))
    words=[word for word in words if word not in stop_words]
    return ' '.join(words)

def preprocess(text):
    text=remove_special_characters(text)
    text=lower_case(text)
    text=remove_stopwords(text)
    return text

device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')

## Define finalized model
model2=BertForSequenceClassification.from_pretrained('/content/drive/MyDrive/model21').to(device)

## Initialize gradio app
import gradio as gr
def predict_score_and_accuracy(text1,text2,num):
        device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        text1=preprocess(text1)
        text2=preprocess(text2)
        input_ids,attention_mask=tokenization(text1,text2)
        with torch.no_grad():
            model2.to(device)
            input_ids=input_ids.to(device)
            attention_masks=attention_mask.to(device)
            outputs=model2(input_ids,attention_masks)
            logits=outputs.logits
            mark_obtained=torch.sigmoid(logits)
            accuracy=torch.argmax(logits,dim=1).item()
            if accuracy==0:
                avg_marks=torch.min(mark_obtained).item()
                avg_marks=round(avg_marks*num,0)
                if avg_marks==num or avg_marks==num-1:
                  accuracy='High'
                elif avg_marks>(num/2) and avg_marks<num-1:
                  accuracy='Medium'
                elif avg_marks<(num/2):
                  accuracy='Low'
            elif accuracy==1:
                avg_marks=torch.mean(mark_obtained).item()
                avg_marks=round(avg_marks*num,0)
                if avg_marks==num or avg_marks==num-1:
                  accuracy='High'
                elif avg_marks>(num/2) and avg_marks<num-1:
                  accuracy='Medium'
                elif avg_marks<(num/2):
                  accuracy='Low'
            elif accuracy==2:
                avg_marks=torch.max(mark_obtained).item()
                avg_marks=round(avg_marks*num,0)
                if avg_marks==num or avg_marks==num-1:
                  accuracy='High'
                elif avg_marks>(num/2) and avg_marks<num-1:
                  accuracy='Medium'
                elif avg_marks<(num/2):
                  accuracy='Low'
        return accuracy,avg_marks

iface = gr.Interface(
    fn=predict_score_and_accuracy,
    inputs=[gr.Textbox(label='actual answer'),gr.Textbox(label='student answer'),gr.Number(label='Maximum Marks')],
    outputs=[gr.Textbox(label='Accuracy'),gr.Number(label='Marks Obtained')]
)

iface.launch(share=True)